
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (1,"Wade","Bryan","Morris","Phasellus","2"),(2,"Clinton","Porter","Tanner","posuere","2"),(3,"Karen","Melton","Frederick","pede.","2"),(4,"Fleur","Jensen","Hart","tellus","2"),(5,"Amir","Ware","Sykes","enim","2"),(6,"Raja","Hyde","Rasmussen","Cum","2"),(7,"Vivian","Reynolds","Vang","sit","2"),(8,"Carol","Rollins","Soto","metus","2"),(9,"Amelia","Knapp","Hendrix","Proin","2"),(10,"Keane","Gilbert","Faulkner","porta","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (11,"Barry","Haley","Reynolds","odio.","2"),(12,"Tasha","Mooney","Estrada","quis","2"),(13,"Michelle","Barnett","Bowen","metus.","2"),(14,"Malcolm","Lamb","Soto","sociis","2"),(15,"Conan","Caldwell","Flowers","aliquet","2"),(16,"Ian","Puckett","Weeks","purus","2"),(17,"Trevor","Morris","Rasmussen","neque.","2"),(18,"Yuri","Alvarado","Weeks","scelerisque","2"),(19,"Lois","Puckett","Le","magna.","2"),(20,"Jacob","Miranda","Guerra","pellentesque,","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (21,"Quail","Whitaker","Sharp","orci,","2"),(22,"Brody","Morrison","Guy","libero","2"),(23,"Winter","Parks","Schneider","a","2"),(24,"Galvin","Barr","Cameron","id,","2"),(25,"Chaim","Casey","Juarez","a","2"),(26,"Naida","Acevedo","Lewis","a","2"),(27,"Hall","Jenkins","Lambert","sed","2"),(28,"Haley","Leblanc","Dean","ipsum","2"),(29,"Destiny","Heath","Prince","orci","2"),(30,"Jameson","Pennington","Morales","tempor,","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (31,"Ferdinand","Savage","Williamson","ac","2"),(32,"Olga","Singleton","Collins","feugiat.","2"),(33,"Mari","Buckley","Gibson","sit","2"),(34,"Keane","Bennett","Pruitt","at","2"),(35,"Ivor","Kennedy","Case","sed,","2"),(36,"Avram","George","Talley","libero.","2"),(37,"Adena","Schultz","York","rutrum","2"),(38,"Ariel","Weeks","Gill","natoque","2"),(39,"Flynn","Santos","Rush","venenatis","2"),(40,"Simone","Phelps","Vazquez","elit","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (41,"Candice","Anthony","Sears","ut","2"),(42,"Myra","Douglas","Davidson","at,","2"),(43,"Jakeem","Cole","Savage","metus","2"),(44,"Olivia","Roth","Bonner","velit.","2"),(45,"Jorden","Brock","Benjamin","urna.","2"),(46,"Anthony","Hurley","Guzman","Praesent","2"),(47,"Edward","Underwood","Reilly","amet","2"),(48,"Rahim","Sears","Chase","nisi","2"),(49,"Darrel","Berry","Hurst","non","2"),(50,"Veronica","Todd","Mejia","sed","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (51,"Portia","Cross","Slater","nec","2"),(52,"Noah","Joyner","Ware","velit","2"),(53,"Serena","Waters","Solomon","nec,","2"),(54,"Ishmael","Maxwell","Donovan","Lorem","2"),(55,"Dai","Richardson","Miranda","tellus","2"),(56,"Cameron","Hardin","Bryan","egestas","2"),(57,"Cadman","Johnson","Velazquez","amet","2"),(58,"Melanie","Davis","Wall","elit.","2"),(59,"Donna","Benton","Alford","dui,","2"),(60,"Devin","Kirby","Hart","tempus","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (61,"Joshua","Wagner","Gould","Aliquam","2"),(62,"Vincent","Medina","Klein","lectus","2"),(63,"Yuli","Cherry","Obrien","amet,","2"),(64,"April","Acevedo","Brown","a","2"),(65,"Quincy","Hopkins","Townsend","mollis.","2"),(66,"Ayanna","Cervantes","Owen","vulputate","2"),(67,"Ainsley","Fuentes","Moon","Aliquam","2"),(68,"Nash","Russell","Holman","dapibus","2"),(69,"Adara","Rowland","Holt","et","2"),(70,"Emi","Petersen","Beasley","dolor","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (71,"Beau","Richardson","Leon","convallis","2"),(72,"Rashad","Perez","Wise","nec","2"),(73,"Kameko","Delaney","Manning","laoreet","2"),(74,"Zephr","Lester","Norton","rutrum","2"),(75,"Amanda","Gill","Mercer","accumsan","2"),(76,"Wynne","Huff","Hampton","Curabitur","2"),(77,"Wynne","Horton","Snow","nisl","2"),(78,"Carter","Carney","Merritt","Cras","2"),(79,"Jessica","Kirkland","Lynn","parturient","2"),(80,"Damon","Manning","Travis","metus","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (81,"Lucas","Lindsey","Delacruz","fermentum","2"),(82,"Hannah","Weiss","Jimenez","porttitor","2"),(83,"Kirby","Mcclain","Montgomery","Etiam","2"),(84,"Kyla","Noble","Norman","Sed","2"),(85,"Rajah","Battle","Cummings","eu","2"),(86,"Nerea","Arnold","Thornton","neque.","2"),(87,"Casey","Trujillo","Merrill","tincidunt","2"),(88,"Edan","Randall","Marks","vulputate","2"),(89,"Yuri","Powers","Mann","consectetuer,","2"),(90,"Quail","Cabrera","Snider","mollis.","2");
INSERT INTO `tbl_usuarioprof` (`usp_id`,`usp_nombre`,`usp_apellido`,`usp_apellido2`,`usp_password`,`tipo_id`) VALUES (91,"Levi","Walsh","Weber","risus.","2"),(92,"Cedric","Humphrey","Mosley","tellus","2"),(93,"Chanda","Bruce","Fry","sapien.","2"),(94,"Skyler","Jefferson","Brady","eu","2"),(95,"Basia","Harmon","Silva","Phasellus","2"),(96,"Burke","Young","Burgess","vel,","2"),(97,"Xantha","Marsh","Camacho","In","2"),(98,"Zachary","Blackwell","Gates","per","2"),(99,"August","Coffey","Fletcher","Donec","2"),(100,"Matthew","Noble","Blackburn","hymenaeos.","2");
